### ISSUE TITLE
Adding as addon breaks ofImage.load()

### ISSUE THREAD

**Issue by javl** [memo/ofxMSATensorFlow#23]
All of the examples work as expected, except for the ones that try to load images. I keep getting a "can't load image" error (also with .png). Trying to figure out what causes this I noticed that when I take a working script, like the `ImageSubsectionExample` that comes with OF and I add `ofxMSATensorFlow` into the `addons.make` file (without adding any code to the project) I start getting the error.

A quick scan of the `ofxMSATensorFlow` source doesn't show any overloaded `ofImage.load()` methods so this seems... odd?

Any suggestions

Running Debian Stretch (testing) and current Git version of OF (master branch).
Working with Sublime Text and `make` on the commandline (no fancy IDE)

**Comment by memo** [comment]
Hey, yea this is a known issue,
https://github.com/memo/ofxMSATensorFlow/wiki/Troubleshooting-&-FAQ

though for me it's only with JPGs. PNGS work fine as you can see in the pics in the readme.

I haven't exactly narrowed down what the issue is with jpgs, but it's not even in ofImage. Opencv's jpg load doesn't work, neither does raw freeimage. 

I've seen some threads around about this, e.g. https://github.com/tensorflow/tensorflow/issues/1924
but haven't dug too deep yet.

**Comment by javl** [comment]
Ah, sorry if this is the same problem. I knew about the .jpg not wanting to load but thought it might be something different because .png doesn't work either. Guess it's just due to my particular setup then. Sorry for the known-issue issue, I'll close it.
